### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by wangwangwar** [wangwangwar/daily-notes#54]
# Cocoa
- [x] Cocoa 自定义 view 如何加入 vc
- [ ] Cocoa vc之间替换/跳转
- [ ] Cocoa 自定义Table View

**Comment by wangwangwar** [comment]
# 动画
- [ ] ios核心动画高级技巧
- [ ] 进度条 - 圆环
- [ ] 进度条 - 粒子
- [ ] 页面中元素动画，如按钮动画，如页面切换动画

**Comment by wangwangwar** [comment]
# FFmpeg
- [ ] 读取文件信息
- [ ] 转换文件格式
- [ ] 在内存中完成转换

**Comment by wangwangwar** [comment]
# 其他
- [ ] 拖放在线视频链接直接下载（然后转换并同步到手机）

**Comment by wangwangwar** [comment]
# youtube-dl

-[ ] 通过NSPipe读取youtube-dl输出的JSON，默认每次读取4096字节，一次读取不完，需要多次读取并组装。

**Comment by wangwangwar** [comment]
# 关于界面
1. 需要看到哪些信息？
2. 需要哪些界面？
3. 界面之间怎么过渡？

**Comment by wangwangwar** [comment]
# Table View
1. Cell 的滑动和删除，3DTransform
